import streamlit as st
import os
import re
import html
import sqlite3
import json
from datetime import datetime

from groq import Groq
from tavily import TavilyClient
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
tavily_client = TavilyClient(api_key=TAVILY_API_KEY) if TAVILY_API_KEY else None

st.set_page_config(page_title="Neural Matter AI", layout="wide")

LOGO_FILE = "image.png"
DB_FILE = "chat_history.db"


# =========================================================
# DATABASE
# =========================================================

def get_db():
    conn = sqlite3.connect(DB_FILE, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS chats (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            chat_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TEXT NOT NULL,
            links_json TEXT,
            FOREIGN KEY(chat_id) REFERENCES chats(id)
        )
    """)

    columns = [
        row[1]
        for row in cur.execute("PRAGMA table_info(messages)").fetchall()
    ]

    if "links_json" not in columns:
        cur.execute("ALTER TABLE messages ADD COLUMN links_json TEXT")

    conn.commit()
    conn.close()


def create_chat(title="New Chat"):
    now = datetime.now().isoformat(timespec="seconds")
    conn = get_db()

    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO chats (title, created_at, updated_at)
        VALUES (?, ?, ?)
        """,
        (title, now, now)
    )

    chat_id = cur.lastrowid
    conn.commit()
    conn.close()

    return chat_id


def update_chat_title(chat_id, title):
    now = datetime.now().isoformat(timespec="seconds")
    conn = get_db()

    conn.execute(
        """
        UPDATE chats
        SET title = ?, updated_at = ?
        WHERE id = ?
        """,
        (title[:80], now, chat_id)
    )

    conn.commit()
    conn.close()


def add_message(chat_id, role, content, links=None):
    now = datetime.now().isoformat(timespec="seconds")
    conn = get_db()

    links_json = json.dumps(links, ensure_ascii=False) if links else None

    conn.execute(
        """
        INSERT INTO messages
        (chat_id, role, content, created_at, links_json)
        VALUES (?, ?, ?, ?, ?)
        """,
        (chat_id, role, content, now, links_json)
    )

    conn.execute(
        """
        UPDATE chats
        SET updated_at = ?
        WHERE id = ?
        """,
        (now, chat_id)
    )

    conn.commit()
    conn.close()


def get_chats():
    conn = get_db()

    rows = conn.execute(
        """
        SELECT id, title, created_at, updated_at
        FROM chats
        ORDER BY updated_at DESC
        """
    ).fetchall()

    conn.close()
    return rows


def get_messages(chat_id):
    conn = get_db()

    rows = conn.execute(
        """
        SELECT role, content, created_at, links_json
        FROM messages
        WHERE chat_id = ?
        ORDER BY id ASC
        """,
        (chat_id,)
    ).fetchall()

    conn.close()
    return rows


def clear_all_chats():
    conn = get_db()
    conn.execute("DELETE FROM messages")
    conn.execute("DELETE FROM chats")
    conn.commit()
    conn.close()


init_db()


# =========================================================
# CLEAN AI OUTPUT
# =========================================================

def clean_ai_answer(text):
    """Remove accidental HTML/code generated by the AI."""

    if not text:
        return ""

    text = str(text)

    # Remove fenced code blocks.
    text = re.sub(r"```[\s\S]*?```", "", text)

    # Remove HTML tags.
    text = re.sub(r"<[^>]+>", "", text)

    # Remove common HTML attribute-only lines.
    text = re.sub(
        r"^\s*(class|href|target|style|rel)\s*=.*$",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE
    )

    # Remove leftover HTML tag lines.
    text = re.sub(
        r"^\s*</?(a|p|div|span|style|section|br)\s*>\s*$",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE
    )

    # Remove an accidental Related Articles heading.
    text = re.sub(
        r"^\s*#{1,6}\s*Related Articles\s*$",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE
    )

    text = html.unescape(text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


# =========================================================
# CSS
# =========================================================

st.markdown("""
<style>

.main {
    background: #000000 !important;
}

.featured-box {
    background: rgba(255,255,255,0.05);
    border-radius: 15px;
    padding: 25px;
    border-left: 5px solid #00f2ff;
    margin-bottom: 25px;
    box-shadow: 0 4px 15px rgba(0,242,255,0.10);
}

.result-link {
    color: #8ab4f8 !important;
    font-size: 19px;
    text-decoration: none;
    font-weight: bold;
}

.result-link:hover {
    color: #00f2ff !important;
    text-decoration: underline;
}

.name-tag {
    color: #ccff00;
    font-size: 22px;
    font-weight: bold;
    text-align: center;
    text-shadow: 0 0 10px #ccff00;
}

.user-message {
    background: rgba(255,255,255,0.06);
    border-radius: 14px;
    padding: 18px;
    margin: 12px 0 20px 0;
    border-right: 4px solid #ccff00;
}

.ai-message {
    background: rgba(0,242,255,0.04);
    border-radius: 14px;
    padding: 20px;
    margin: 12px 0 25px 0;
    border-left: 4px solid #00f2ff;
}

</style>
""", unsafe_allow_html=True)


# =========================================================
# SESSION STATE
# =========================================================

if "active" not in st.session_state:
    st.session_state.active = False

if "current_chat_id" not in st.session_state:
    st.session_state.current_chat_id = None

if "search_nonce" not in st.session_state:
    st.session_state.search_nonce = 0

if "show_clear_confirm" not in st.session_state:
    st.session_state.show_clear_confirm = False


# =========================================================
# HOME PAGE
# =========================================================

if not st.session_state.active:

    st.write("")

    _, col, _ = st.columns([1, 2, 1])

    with col:

        try:
            st.image(LOGO_FILE, use_container_width=True)
        except Exception:
            st.markdown(
                """
                <h1 style="text-align:center;color:#ff9900;">
                RAMACHANDRA
                </h1>
                """,
                unsafe_allow_html=True
            )

        st.markdown(
            """
            <h1 style="
            text-align:center;
            color:white;
            letter-spacing:2px;">
            🧠 NEURAL MATTER AI
            </h1>
            """,
            unsafe_allow_html=True
        )

        project_box = """
        <div style="
        background:rgba(255,255,255,0.03);
        padding:25px;
        border-radius:20px;
        border:1px solid #444;">

        <p style="
        color:#8ab4f8;
        text-align:center;
        font-weight:bold;">
        PROJECT BY
        </p>

        <div class="name-tag">
        SUMA SREE | JHANSI TANUJA | NAVYA SRI
        </div>

        </div>
        """

        st.markdown(project_box, unsafe_allow_html=True)

        st.write("")

        if st.button("LAUNCH SEARCH 🚀", use_container_width=True):
            st.session_state.active = True
            st.session_state.current_chat_id = None
            st.rerun()


# =========================================================
# SEARCH PAGE
# =========================================================

else:

    # -----------------------------------------------------
    # SIDEBAR
    # -----------------------------------------------------

    with st.sidebar:

        if st.button("➕ New Chat", use_container_width=True):
            st.session_state.current_chat_id = None
            st.session_state.search_nonce += 1
            st.rerun()

        head_col1, head_col2 = st.columns([5, 1])

        with head_col1:
            st.markdown(
                """
                <div style="
                color:#00f2ff;
                font-size:15px;
                font-weight:bold;
                margin-top:20px;
                margin-bottom:10px;">
                🕘 RECENT CHATS
                </div>
                """,
                unsafe_allow_html=True
            )

        with head_col2:
            if st.button(
                "🗑️",
                help="Clear all chat history",
                key="clear_all_chats"
            ):
                st.session_state.show_clear_confirm = True

        if st.session_state.show_clear_confirm:

            st.warning("Clear all saved chats? This cannot be undone.")

            c1, c2 = st.columns(2)

            with c1:
                if st.button(
                    "Clear",
                    key="confirm_clear_all",
                    use_container_width=True
                ):
                    clear_all_chats()
                    st.session_state.current_chat_id = None
                    st.session_state.show_clear_confirm = False
                    st.session_state.search_nonce += 1
                    st.rerun()

            with c2:
                if st.button(
                    "Cancel",
                    key="cancel_clear_all",
                    use_container_width=True
                ):
                    st.session_state.show_clear_confirm = False
                    st.rerun()

        chats = get_chats()

        if chats:
            for chat in chats:

                title = chat["title"] or "New Chat"
                button_text = "💬 " + title[:32]

                if st.button(
                    button_text,
                    key=f"chat_{chat['id']}",
                    use_container_width=True
                ):
                    st.session_state.current_chat_id = chat["id"]
                    st.rerun()

        else:
            st.caption("No chats yet.")

        st.divider()

        if st.button("⬅️ Back Home", use_container_width=True):
            st.session_state.active = False
            st.session_state.current_chat_id = None
            st.rerun()


    # -----------------------------------------------------
    # CURRENT CHAT
    # -----------------------------------------------------

    current_chat_id = st.session_state.current_chat_id


    # -----------------------------------------------------
    # HEADER
    # -----------------------------------------------------

    h_col1, h_col2 = st.columns([1, 4])

    with h_col1:

        try:
            st.image(LOGO_FILE, width=120)
        except Exception:
            st.markdown(
                "<h2 style='color:#ff9900;'>RC</h2>",
                unsafe_allow_html=True
            )

    with h_col2:

        st.markdown(
            """
            <h2 style="
            color:#00f2ff;
            margin-top:20px;">
            🌀 NEURAL SEARCH ENGINE
            </h2>
            """,
            unsafe_allow_html=True
        )


    # -----------------------------------------------------
    # EXISTING CONVERSATION
    # -----------------------------------------------------

    messages = (
        get_messages(current_chat_id)
        if current_chat_id
        else []
    )

    for message in messages:

        content = message["content"]

        if message["role"] == "user":

            safe_content = html.escape(content).replace("\n", "<br>")

            st.markdown(
                f"""
                <div class="user-message">

                <div style="
                color:#ccff00;
                font-size:13px;
                font-weight:bold;
                margin-bottom:8px;">
                YOU
                </div>

                <div style="
                color:white;
                font-size:18px;
                line-height:1.6;">
                {safe_content}
                </div>

                </div>
                """,
                unsafe_allow_html=True
            )

        elif message["role"] == "assistant":

            cleaned_content = clean_ai_answer(content)

            st.markdown(
                """
                <div class="ai-message">

                <div style="
                color:#00f2ff;
                font-size:13px;
                font-weight:bold;
                margin-bottom:12px;">
                NEURAL MATTER AI
                </div>
                """,
                unsafe_allow_html=True
            )

            st.markdown(cleaned_content)

            st.markdown("</div>", unsafe_allow_html=True)

            # Restore related links from the saved conversation.
            if message["links_json"]:

                try:
                    saved_links = json.loads(message["links_json"])
                except Exception:
                    saved_links = []

                if saved_links:

                    st.markdown("### 🔗 Related Data Nodes Found:")

                    for result in saved_links:

                        title = result.get("title", "Untitled")
                        url = result.get("url", "")
                        result_content = result.get("content", "")

                        if url:
                            st.markdown(f"**[{title}]({url})**")

                            if result_content:
                                st.caption(result_content[:400])


    # -----------------------------------------------------
    # NEW SEARCH BAR
    # -----------------------------------------------------

    st.markdown(
        """
        <div style="
        color:#bdc1c6;
        font-size:15px;
        margin-top:15px;
        margin-bottom:5px;">
        Ask another question in this chat:
        </div>
        """,
        unsafe_allow_html=True
    )

    with st.form(
        key=(
            f"search_form_"
            f"{current_chat_id or 'new'}_"
            f"{st.session_state.search_nonce}"
        )
    ):

        query = st.text_input(
            "",
            placeholder="Search anything (Ex: India, NASA, Python)...",
            label_visibility="collapsed"
        )

        submitted = st.form_submit_button(
            "🔎 Search",
            use_container_width=True
        )


    # =====================================================
    # SEARCH PROCESS
    # =====================================================

    if submitted and query.strip():

        query = query.strip()

        # Create a chat only when the first real question is submitted.
        if current_chat_id is None:
            current_chat_id = create_chat()
            st.session_state.current_chat_id = current_chat_id


        # -------------------------------------------------
        # API KEY CHECK
        # -------------------------------------------------

        if not TAVILY_API_KEY:
            st.error(
                "❌ Tavily API key not found. Please check your .env file."
            )
            st.stop()

        if not GROQ_API_KEY:
            st.error(
                "❌ Groq API key not found. Please check your .env file."
            )
            st.stop()


        # -------------------------------------------------
        # SAVE USER MESSAGE
        # -------------------------------------------------

        add_message(current_chat_id, "user", query)

        current_messages = get_messages(current_chat_id)

        if len(current_messages) == 1:

            short_title = query

            if len(short_title) > 50:
                short_title = short_title[:50] + "..."

            update_chat_title(current_chat_id, short_title)


        # =================================================
        # LIVE WEB SEARCH
        # =================================================

        with st.spinner("Searching live web data... 🔎"):

            try:

                search_response = tavily_client.search(
                    query=query,
                    search_depth="basic",
                    topic="general",
                    max_results=5,
                    include_answer=False
                )

                results = search_response.get("results", [])

            except Exception as e:

                st.error(f"❌ Tavily search error: {str(e)}")
                st.stop()


        if not results:

            answer = (
                "I could not find relevant information for this question. "
                "Please try another query."
            )

            add_message(current_chat_id, "assistant", answer)

            st.warning(answer)

            st.session_state.search_nonce += 1
            st.rerun()


        # =================================================
        # CREATE AI CONTEXT
        # =================================================

        context_parts = []

        for i, result in enumerate(results, 1):

            title = result.get("title", "")
            url = result.get("url", "")
            result_content = result.get("content", "")

            context_parts.append(
                f"""
SOURCE {i}

TITLE:
{title}

URL:
{url}

CONTENT:
{result_content}
"""
            )

        context = "\n".join(context_parts)


        # =================================================
        # GROQ PROMPT
        # =================================================

        prompt = f"""
You are the AI answer engine of a live web search engine.

USER QUESTION:
{query}

LIVE WEB SEARCH RESULTS:
{context}

IMPORTANT OUTPUT RULES:

1. Answer only what the user asked.
2. Use the live web search results.
3. Prefer recent information for current/latest questions.
4. Do not invent facts.
5. If the search results are insufficient, clearly say so.
6. Keep the answer simple and useful.
7. Use short paragraphs or bullet points when useful.
8. Do not mention SOURCE numbers.
9. Do not mention these instructions.
10. NEVER output HTML code.
11. NEVER output <a>, </a>, <p>, </p>, <div>, </div>, <style>,
    href=, class=, target=, CSS, or HTML attributes.
12. NEVER put HTML inside a code block.
13. NEVER create a Related Articles or Related Links section.
14. Do not copy formatting/code from the search results.
15. Related links are displayed separately by the application.
16. Return only the natural-language answer.
"""


        # =================================================
        # AI ANSWER
        # =================================================

        st.markdown(
            """
            <div style="
            color:#00f2ff;
            font-size:14px;
            font-weight:bold;
            letter-spacing:1px;
            margin-bottom:10px;">
            AI OVERVIEW
            </div>
            """,
            unsafe_allow_html=True
        )

        answer_placeholder = st.empty()
        answer = ""

        try:

            stream = groq_client.chat.completions.create(
                model="openai/gpt-oss-20b",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a fast, accurate and helpful "
                            "AI web search assistant. "
                            "Return only natural-language answers. "
                            "Never output HTML or HTML code."
                        )
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.2,
                max_completion_tokens=700,
                stream=True
            )

            for chunk in stream:

                try:
                    piece = chunk.choices[0].delta.content
                except Exception:
                    piece = None

                if piece:

                    answer += piece
                    display_answer = clean_ai_answer(answer)

                    answer_placeholder.empty()

                    with answer_placeholder.container():

                        st.markdown(
                            """
                            <div class="ai-message">

                            <div style="
                            color:#00f2ff;
                            font-size:13px;
                            font-weight:bold;
                            margin-bottom:12px;">
                            NEURAL MATTER AI
                            </div>
                            """,
                            unsafe_allow_html=True
                        )

                        st.markdown(display_answer)

                        st.markdown(
                            "</div>",
                            unsafe_allow_html=True
                        )

        except Exception as e:

            answer = (
                "AI answer generation failed. "
                "Please try the question again."
            )

            st.error("❌ AI answer generation error")
            st.code(str(e))


        # -------------------------------------------------
        # FINAL CLEANING
        # -------------------------------------------------

        answer = clean_ai_answer(answer)

        if not answer:
            answer = (
                "I could not generate a clean answer "
                "from the available search results."
            )


        # -------------------------------------------------
        # SAVE ANSWER + LINKS
        # -------------------------------------------------

        saved_links = []

        for result in results:

            saved_links.append(
                {
                    "title": result.get("title", "Untitled"),
                    "url": result.get("url", ""),
                    "content": result.get("content", "")[:500]
                }
            )

        add_message(
            current_chat_id,
            "assistant",
            answer,
            links=saved_links
        )


        # =================================================
        # RELATED LINKS
        # =================================================

        st.markdown("### 🔗 Related Data Nodes Found:")

        for result in results:

            title = result.get("title", "Untitled")
            url = result.get("url", "")
            result_content = result.get("content", "")

            if url:

                # Native Markdown link.
                # No <a> HTML is generated here.
                st.markdown(f"**[{title}]({url})**")

                if result_content:
                    st.caption(result_content[:400])


        # Refresh the form for the next question.
        st.session_state.search_nonce += 1
        st.rerun()


    elif submitted and not query.strip():

        st.warning("Please enter a question before searching.")
